language: java
jdk: openjdk11
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259


# This skips the mvn install that is otherwise run (implausibly, the setting has to be "true")
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
#install: true

script:
  - mvn test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
#  - mvn package -B -Dmatsim.preferLocalDtds=true
# --fail-at-end
# -Dmaven.test.redirectTestOutputToFile 
env:
  global:
    - MAVEN_OPTS="-Xmx2g"
cache:
  directories:
  - $HOME/.m2

